# Generated by Django 4.2.30 on 2026-08-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('email_uid', models.CharField(blank=True, default='', max_length=100)),
                ('asunto', models.CharField(blank=True, default='', max_length=500)),
                ('remitente', models.CharField(blank=True, default='', max_length=320)),
                ('fecha_correo', models.DateTimeField(blank=True, null=True)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('ok', 'Órdenes creadas'), ('omitido_cotizacion', 'Omitido — cotización'), ('omitido_sin_adjuntos', 'Omitido — sin adjuntos válidos'), ('omitido_orden', "Omitido — todos los adjuntos eran 'orden'"), ('alerta_sin_regla', 'Alerta — sin regla de cliente'), ('error', 'Error')], max_length=30)),
                ('ordenes', models.JSONField(blank=True, default=list)),
                ('detalle', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-procesado_en'],
            },
        ),
    ]
