# Generated by Django 4.2.30 on 2026-05-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('final', 'Cliente Final'), ('terciario', 'Cliente Terciario')], default='final', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('gramaje', models.PositiveIntegerField(help_text='g/m²')),
                ('material', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='COP por pliego', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'gramaje'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(max_length=300)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_cliente', models.CharField(choices=[('final', 'Cliente Final'), ('terciario', 'Cliente Terciario')], default='final', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida a OP')], default='borrador', max_length=20)),
                ('molde_ancho', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('molde_alto', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('pliego_tipo', models.CharField(default='70x100', max_length=20)),
                ('pliego_w', models.DecimalField(decimal_places=2, default=70, max_digits=7)),
                ('pliego_h', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('precio_pliego', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_papel_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_unitario_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_total_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_costos_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('subtotal_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('condicion_pago', models.CharField(choices=[('mismo', 'Mismo día'), ('8', '8 días'), ('30', '30 días'), ('custom', 'Personalizado')], default='30', max_length=20)),
                ('condicion_custom', models.CharField(blank=True, default='', max_length=300)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='cotizaciones.cliente')),
                ('papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizaciones.papel')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='cotizaciones.cotizacion')),
            ],
            options={
                'ordering': ['proceso_id'],
                'unique_together': {('cotizacion', 'proceso_id')},
            },
        ),
    ]
