# Generated by Django 4.2.30 on 2026-05-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cliente_nit_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sobrante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
