# Generated by Django 4.2.30 on 2026-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_add_sobrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='corte_final_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='corte_final_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='corte_inicial_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='corte_inicial_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
