# Generated by Django 4.2.30 on 2026-05-26 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0007_documento_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('remisionada', 'Remisionada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('tipo_cliente_op', models.CharField(choices=[('final', 'Cliente Final'), ('terciario', 'Cliente Terciario')], default='final', max_length=20)),
                ('condicion_cobro_terciario', models.CharField(blank=True, choices=[('op', 'Solo OP'), ('remision', 'Remisión'), ('factura', 'Factura')], default='', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_pliegos', models.PositiveIntegerField(default=0)),
                ('papel_referencia', models.CharField(blank=True, default='', max_length=200)),
                ('corte_inicial', models.CharField(blank=True, default='', max_length=100)),
                ('corte_final', models.CharField(blank=True, default='', max_length=100)),
                ('medida_producto', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad_impresion', models.PositiveIntegerField(default=0)),
                ('total_costos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('condicion_pago', models.CharField(choices=[('mismo_dia', 'Mismo Día'), ('8_dias', '8 Días'), ('30_dias', '30 Días'), ('60_dias', '60 Días')], default='mismo_dia', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='cotizaciones.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='cotizaciones.cotizacion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='OpProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maquina_id', models.CharField(blank=True, default='', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('unidades_completadas', models.PositiveIntegerField(default=0)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_op', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='cotizaciones.ordenproduccion')),
            ],
            options={
                'ordering': ['proceso_id'],
                'unique_together': {('orden', 'proceso_id')},
            },
        ),
    ]
