# Generated by Django 4.2.30 on 2026-06-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0009_rebuild_ordenproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opproceso',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opproceso',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(choices=[('troquel', 'Troquel'), ('guillotina', 'Guillotina')], max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_maquina', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_maquina', to='cotizaciones.ordenproduccion')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
