# Generated by Django 4.2.30 on 2026-06-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_opproceso_completado_opproceso_completado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaquina',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_maquina', to='cotizaciones.ordenproduccion'),
        ),
    ]
