# Generated by Django 4.2.30 on 2026-06-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_precios(apps, schema_editor):
    PrecioTroquel = apps.get_model("cotizaciones", "PrecioTroquel")
    # Defaults "aleatorios" por ahora (COP por cm); el Admin los ajusta luego.
    defaults = {"corte": 12, "score": 18, "hendido": 25, "caucho": 40}
    for tipo, precio in defaults.items():
        PrecioTroquel.objects.get_or_create(tipo=tipo, defaults={"precio_unitario": precio})


def unseed_precios(apps, schema_editor):
    PrecioTroquel = apps.get_model("cotizaciones", "PrecioTroquel")
    PrecioTroquel.objects.filter(tipo__in=["corte", "score", "hendido", "caucho"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0011_alter_registromaquina_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioTroquel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('corte', 'Corte'), ('score', 'Score'), ('hendido', 'C. Hendido'), ('caucho', 'Caucho')], max_length=20, unique=True)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, help_text='COP por cm', max_digits=12)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TroquelModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='troquel_modelos/')),
                ('troquel_numero', models.CharField(blank=True, default='', max_length=50)),
                ('pinza', models.CharField(blank=True, default='', max_length=100)),
                ('madera', models.CharField(blank=True, default='', max_length=100)),
                ('cuchilla_puntos', models.CharField(blank=True, default='', max_length=100)),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('espejo', models.BooleanField(default=False)),
                ('dimensiones', models.TextField(blank=True, default='')),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('corte_cm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('score_cm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('hendido_cm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troquel_modelo', to='cotizaciones.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoCuchillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuchilla_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grafa_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dos_puntos', models.BooleanField(default=False)),
                ('tres_puntos', models.BooleanField(default=False)),
                ('perfo', models.BooleanField(default=False)),
                ('ch', models.CharField(blank=True, default='', max_length=100)),
                ('sac', models.CharField(blank=True, default='', max_length=100)),
                ('gan', models.CharField(blank=True, default='', max_length=100)),
                ('caucho_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desperdicio', models.CharField(blank=True, default='', max_length=200)),
                ('tiempo_encalado', models.CharField(blank=True, default='', max_length=50)),
                ('tiempo_encuchillado', models.CharField(blank=True, default='', max_length=50)),
                ('tiempo_encauchado', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_cuchillas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos_cuchillas', to='cotizaciones.ordenproduccion')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.RunPython(seed_precios, unseed_precios),
    ]
