# Generated by Django 4.2.30 on 2026-06-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_seed_operador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troquelmodelo',
            name='dimensiones',
        ),
    ]
