# Generated by Django 4.2.30 on 2026-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_remove_troquelmodelo_dimensiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatocuchillas',
            name='tiempo_encalado',
        ),
        migrations.RemoveField(
            model_name='formatocuchillas',
            name='tiempo_encauchado',
        ),
        migrations.RemoveField(
            model_name='formatocuchillas',
            name='tiempo_encuchillado',
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='tiempo_encalado_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='tiempo_encauchado_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='tiempo_encuchillado_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
