# Generated by Django 4.2.30 on 2026-06-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_remove_formatocuchillas_tiempo_encalado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
