# Generated by Django 4.2.30 on 2026-06-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_remision_cliente_ciudad_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='consolidada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remision',
            name='consolidada_en_remision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_consolidadas', to='cotizaciones.remision'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('liquidada', 'Liquidada'), ('consolidada', 'Consolidada')], default='pendiente', max_length=20),
        ),
    ]
