# Generated by Django 4.2.30 on 2026-07-03 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _aprobar_formatos_existentes(apps, schema_editor):
    # Formatos previos ya completaron el troquel bajo el flujo antiguo:
    # no deben entrar retroactivamente a la cola de aprobación.
    FormatoCuchillas = apps.get_model("cotizaciones", "FormatoCuchillas")
    FormatoCuchillas.objects.all().update(estado="aprobado")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0018_remision_consolidada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatocuchillas',
            name='devolucion_motivo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('devuelto', 'Devuelto al operador')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_cuchillas_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_aprobar_formatos_existentes, migrations.RunPython.noop),
    ]
