# Generated by Django 4.2.30 on 2026-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_formatocuchillas_devolucion_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatocuchillas',
            name='cauchos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='ch_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='ch_medida',
            field=models.CharField(blank=True, choices=[('3x3', '3x3'), ('4x4', '4x4'), ('6x6', '6x6'), ('8x8', '8x8'), ('10x10', '10x10')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='desperdicio_mm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='perfo_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='perfo_medida',
            field=models.CharField(blank=True, choices=[('1x1', '1x1'), ('2x1', '2x1'), ('2x2', '2x2'), ('3x1', '3x1'), ('3x2', '3x2'), ('3x3', '3x3'), ('4x1', '4x1'), ('4x2', '4x2'), ('4x3', '4x3'), ('4x4', '4x4'), ('6x6', '6x6'), ('10x10', '10x10')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='sac_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='sac_medida',
            field=models.CharField(blank=True, choices=[('1', '1 (extensor)'), ('2', '2 (extensor)'), ('3', '3 (extensor)'), ('4', '4 (extensor)'), ('5', '5 (extensor)'), ('6', '6 (extensor)'), ('7', '7 (extensor)'), ('8', '8 (extensor)'), ('9', '9 (extensor)'), ('10', '10 (extensor)'), ('11', '11 (tubo)'), ('12', '12 (tubo)'), ('13', '13 (tubo)'), ('14', '14 (tubo)'), ('15', '15 (tubo)')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='troquelmodelo',
            name='precio_caucho',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='troquelmodelo',
            name='precio_corte',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='troquelmodelo',
            name='precio_hendido',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='troquelmodelo',
            name='precio_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='formatocuchillas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('devuelto', 'Devuelto al operador'), ('borrador', 'Borrador (envío cancelado)')], default='pendiente', max_length=20),
        ),
    ]
