# Generated by Django 4.2.30 on 2026-07-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0021_copy_precios_and_cauchos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioTroquel',
        ),
        migrations.RemoveField(
            model_name='formatocuchillas',
            name='caucho_cm',
        ),
    ]
