# Generated by Django 4.2.30 on 2026-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0023_rename_grupolam_blucolan'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatocuchillas',
            name='cuchilla_puntos',
            field=models.CharField(blank=True, choices=[('2', '2 puntos'), ('3', '3 puntos')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='grafa_altura',
            field=models.CharField(blank=True, choices=[('23.4', '23,4 mm'), ('23.3', '23,3 mm')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='formatocuchillas',
            name='grafa_puntos',
            field=models.CharField(blank=True, choices=[('2', '2 puntos'), ('3', '3 puntos')], default='', max_length=1),
        ),
    ]
