# Generated by Django 4.2.30 on 2026-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0024_formatocuchillas_cuchilla_puntos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatocuchillas',
            name='sac_medida',
            field=models.CharField(blank=True, choices=[('1', '1 (expulsor)'), ('2', '2 (expulsor)'), ('3', '3 (expulsor)'), ('4', '4 (expulsor)'), ('5', '5 (expulsor)'), ('6', '6 (expulsor)'), ('7', '7 (expulsor)'), ('8', '8 (expulsor)'), ('9', '9 (expulsor)'), ('10', '10 (expulsor)'), ('11', '11 (tubo)'), ('12', '12 (tubo)'), ('13', '13 (tubo)'), ('14', '14 (tubo)'), ('15', '15 (tubo)')], default='', max_length=5),
        ),
    ]
