# Generated by Django 4.2.30 on 2026-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0025_alter_formatocuchillas_sac_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='troquelmodelo',
            name='costos_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
