# Generated by Django 4.2.30 on 2026-07-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0026_troquelmodelo_costos_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='remision_solicitada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='remision_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
