# Generated by Django 4.2.30 on 2026-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_normalizar_nombres_cliente_nfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='opproceso',
            name='visible_operador',
            field=models.BooleanField(default=False),
        ),
    ]
