# Generated by Django 4.2.30 on 2026-07-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0030_opproceso_visible_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='mostrar_valores',
            field=models.BooleanField(default=False),
        ),
    ]
