# Generated by Django 4.2.30 on 2026-07-22 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0032_opproceso_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=300)),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=300)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='cotizaciones.ordenproduccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_orden', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
