# Generated by Django 4.2.30 on 2026-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0033_ordencambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precios_troquel',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
