# Generated by Django 4.2.30 on 2026-08-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0034_cliente_precios_troquel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='opciones',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
