# Generated by Django 4.2.30 on 2026-08-12 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0035_cotizacion_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='generada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remision',
            name='generada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_generadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
