# Generated by Django 4.2.30 on 2026-08-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0039_formatocuchillas_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatocuchillas',
            name='perfo_medida',
            field=models.CharField(blank=True, choices=[('1x1', '1x1'), ('2x1', '2x1'), ('2x2', '2x2'), ('3x1', '3x1'), ('3x2', '3x2'), ('3x3', '3x3'), ('4x1', '4x1'), ('4x2', '4x2'), ('4x3', '4x3'), ('4x4', '4x4'), ('6x6', '6x6'), ('10x10', '10x10'), ('GLUE', 'GLUE')], default='', max_length=10),
        ),
    ]
