# Generated by Django 4.2.30 on 2026-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0040_alter_formatocuchillas_perfo_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_normalizado',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='troquelmodelo',
            name='nota_cliente',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
