# Generated by Django 4.2.30 on 2026-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0040_alter_formatocuchillas_perfo_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatocuchillas',
            name='sacabocados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
