# Generated by Django 4.2.30 on 2026-08-21 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0042_copy_sacabocados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(choices=[('impresora', 'Impresora'), ('laminadora', 'Laminadora'), ('barnizadora', 'Barnizadora'), ('troqueladora', 'Troqueladora')], max_length=20)),
                ('proceso_id', models.CharField(max_length=50)),
                ('cantidad_realizada', models.PositiveIntegerField(default=0)),
                ('cantidad_esperada', models.PositiveIntegerField(default=0)),
                ('faltante', models.BooleanField(default=False)),
                ('tamano', models.CharField(blank=True, choices=[('pliego', 'Pliego completo'), ('medio_pliego', '1/2 pliego'), ('cuarto_pliego', '1/4 pliego'), ('octavo_pliego', '1/8 pliego'), ('carta', 'Carta'), ('media_carta', '1/2 carta'), ('cuarto_carta', '1/4 carta'), ('otro', 'Otro')], default='', max_length=20)),
                ('tamano_otro', models.CharField(blank=True, default='', max_length=120)),
                ('tiro_active', models.BooleanField(default=False)),
                ('tiro_colores_num', models.PositiveSmallIntegerField(default=0)),
                ('tiro_colores_desc', models.CharField(blank=True, default='', max_length=200)),
                ('retiro_active', models.BooleanField(default=False)),
                ('retiro_colores_num', models.PositiveSmallIntegerField(default=0)),
                ('retiro_colores_desc', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_laminado', models.CharField(blank=True, choices=[('mate', 'Mate'), ('brillante', 'Brillante'), ('metalizado', 'Metalizado')], default='', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_proceso', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_proceso', to='cotizaciones.ordenproduccion')),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cantidad_faltante', 'Cantidad por debajo de lo esperado')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('leida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='cotizaciones.ordenproduccion')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='cotizaciones.registroproceso')),
            ],
            options={
                'ordering': ['-creada', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='registroproceso',
            index=models.Index(fields=['estacion', '-fecha_hora'], name='cotizacione_estacio_1c9b73_idx'),
        ),
        migrations.AddIndex(
            model_name='registroproceso',
            index=models.Index(fields=['orden', 'estacion'], name='cotizacione_orden_i_9b0afe_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leida_en', '-creada'], name='cotizacione_leida_e_f1649e_idx'),
        ),
    ]
