# Generated by Django 4.2.30 on 2026-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0042_merge_clientes_duplicados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_normalizado',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, unique=True),
        ),
    ]
