# Generated by Django 4.2.30 on 2026-08-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0043_registroproceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproceso',
            name='estacion',
            field=models.CharField(choices=[('guillotina', 'Guillotina · Corte inicial'), ('impresora', 'Impresora'), ('laminadora', 'Laminadora'), ('barnizadora', 'Barnizadora'), ('troqueladora', 'Troqueladora'), ('guillotina_final', 'Guillotina · Corte final')], max_length=20),
        ),
    ]
