# Generated by Django 4.2.30 on 2026-08-22 13:45

from django.db import migrations, models


def backfill_tiene_troquel(apps, schema_editor):
    Remision = apps.get_model("cotizaciones", "Remision")
    OpProceso = apps.get_model("cotizaciones", "OpProceso")
    ordenes_con_troquel = set(
        OpProceso.objects.filter(proceso_id="troquel", active=True).values_list("orden_id", flat=True)
    )
    remisiones_a_marcar = Remision.objects.filter(orden_id__in=ordenes_con_troquel)
    remisiones_a_marcar.update(tiene_troquel=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0044_alter_registroproceso_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='tiene_troquel',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_tiene_troquel, migrations.RunPython.noop),
    ]
