# Generated by Django 4.2.30 on 2026-08-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0046_remove_opproceso_visible_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='papel_manual_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='papel_manual_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
