# Generated by Django 4.2.30 on 2026-08-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0043_cliente_nombre_normalizado_unique'),
        ('cotizaciones', '0048_formatocuchillas_gan_tipos'),
    ]

    operations = [
    ]
