# Generated by Django 4.2.30 on 2026-09-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0049_merge_20260831_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='remision_descartada_operador_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
