# Generated by Django 4.2.30 on 2026-09-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0050_ordenproduccion_remision_descartada_operador_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_general', models.BooleanField(default=False, verbose_name='Acceso general (producción + remisión)')),
                ('es_troquelador', models.BooleanField(default=False, verbose_name='Troquelador (módulo Troqueles)')),
                ('es_estaciones', models.BooleanField(default=False, verbose_name='Estaciones (Impresora, Laminadora, Barnizadora, Troqueladora)')),
                ('es_guillotina', models.BooleanField(default=False, verbose_name='Guillotina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
