# Generated by Django 4.2.30 on 2026-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0052_perfil_operador_general_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='tamano',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
