# Generated by Django 4.2.30 on 2026-09-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0053_ordenproduccion_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatocuchillas',
            name='madera_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
