# Generated by Django 4.2.30 on 2026-09-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0054_formatocuchillas_madera_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproceso',
            name='monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
