# Generated by Django 4.2.30 on 2026-09-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0055_registroproceso_monto_cobrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cantidad_faltante', 'Cantidad por debajo de lo esperado'), ('formato_devuelto', 'Formato de cuchillas devuelto')], max_length=30),
        ),
    ]
