# Generated by Django 4.2.30 on 2026-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0056_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproceso',
            name='tipo_metalizado',
            field=models.CharField(blank=True, choices=[('plateado', 'Plateado'), ('dorado', 'Dorado'), ('rosado', 'Rosado'), ('otros', 'Otros')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registroproceso',
            name='tipo_metalizado_otro',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
