# Generated by Django 4.2.30 on 2026-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0058_formatocuchillas_madera_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproceso',
            name='tamano',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
