# Generated by Django 4.2.30 on 2026-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0059_alter_registroproceso_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproceso',
            name='tamano',
            field=models.CharField(blank=True, choices=[('pliego', 'Pliego completo'), ('medio_pliego', '1/2 pliego'), ('cuarto_pliego', '1/4 pliego'), ('octavo_pliego', '1/8 pliego'), ('carta', 'Carta'), ('media_carta', '1/2 carta'), ('cuarto_carta', '1/4 carta'), ('otro', 'Otro')], default='', max_length=20),
        ),
    ]
